#!/usr/bin/env bash

# Copyright 2016 Patrick Haun
# Edited: Denis Kadyshev
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

layout=`xkb-switch | sed -re's/\([^\)]+\)//g' | tr [a-z] [A-Z]`

us_color=#aaaaff
rs_color=#779977
default_color=#aaaaaa

case $layout in
    US)
        color=$us_color
        ;;
    RS)
        color=$rs_color
        ;;
    *)
        color=$default_color
        ;;
esac

case $BLOCK_BUTTON in
    1) case $layout in
	    US)
		setxkbmap -layout rs
		layout="RS"
		color=$rs_color
		;;
	    *)
		setxkbmap -layout us
		layout="US"
		color=$us_color
	esac
        ;;
    *)
esac

echo $layout
echo $layout
echo $color

